import { Navbar01 } from '@/components/ui/navbar';
import './global.css';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar01 />
        {children}
      </body>
    </html>
  );
}
